//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Mensagens {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MensagemAlerta {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagemAlerta() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetShop.Mensagens.MensagemAlerta", typeof(MensagemAlerta).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data hora do agendamento não foi preenchida.
        /// </summary>
        internal static string DataAgendamentoNaoPreenchida {
            get {
                return ResourceManager.GetString("DataAgendamentoNaoPreenchida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de nascimento inserida é a mesma da atual, está correto?.
        /// </summary>
        internal static string DataNascimentoIgualAtual {
            get {
                return ResourceManager.GetString("DataNascimentoIgualAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de nascimento não preenchida.
        /// </summary>
        internal static string DataNascimentoNaoPreenchida {
            get {
                return ResourceManager.GetString("DataNascimentoNaoPreenchida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo de login é obrigatório.
        /// </summary>
        internal static string LoginNaoPreenchido {
            get {
                return ResourceManager.GetString("LoginNaoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modalidade do agendamento não foi preenchida.
        /// </summary>
        internal static string ModalidadeAgendamentoNaoPreenchida {
            get {
                return ResourceManager.GetString("ModalidadeAgendamentoNaoPreenchida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do animal a ser agendado não foi preenchido.
        /// </summary>
        internal static string NomeAnimalAgendadoNaoPreenchido {
            get {
                return ResourceManager.GetString("NomeAnimalAgendadoNaoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do animal não preenchido.
        /// </summary>
        internal static string NomeAnimalNaoPreenchido {
            get {
                return ResourceManager.GetString("NomeAnimalNaoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do tutor do animal não preenchido.
        /// </summary>
        internal static string NomeTutorAnimalNaoPreenchido {
            get {
                return ResourceManager.GetString("NomeTutorAnimalNaoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número de telefone do tutor não preenchido.
        /// </summary>
        internal static string NumeroTutorNaoPreenchido {
            get {
                return ResourceManager.GetString("NumeroTutorNaoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Raça do animal não preenchida.
        /// </summary>
        internal static string RacaAnimalNaoPreenchida {
            get {
                return ResourceManager.GetString("RacaAnimalNaoPreenchida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo de senha é obrigatório.
        /// </summary>
        internal static string SenhaNaoPreenchida {
            get {
                return ResourceManager.GetString("SenhaNaoPreenchida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sexo do animal não preenchido.
        /// </summary>
        internal static string SexoAnimalNaoPreenchido {
            get {
                return ResourceManager.GetString("SexoAnimalNaoPreenchido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo do animal não preenchido.
        /// </summary>
        internal static string TipoAnimalNaoPreenchido {
            get {
                return ResourceManager.GetString("TipoAnimalNaoPreenchido", resourceCulture);
            }
        }
    }
}
